### ISSUE TITLE
Unknown variable "unmasked".

### ISSUE THREAD

**Issue by bvarjavand** [Upward-Spiral-Science/team1#1]
@jovo 
The 4th column in our data contains data for an "unmasked" variable. Explanation of its role would be helpful. We found a correlation coefficient of 0.8962 between the "unmasked" and "synapses" variables, but would like to know the actual meaning behind the "unmasked" variable.

Code we used to find the correlation coefficient, in Python:

csv = genfromtext('output.csv','delimiter' = ',')[1:]
corr = np.corrcoef(csv[:,3],csv[:,4])
print corr

**Comment by jovo** [comment]
Check Readme in your folder in data repo.
