### ISSUE TITLE
Inhibitory vs Excitatory Neurons

### ISSUE THREAD

**Issue by bvarjavand** [Upward-Spiral-Science/team1#2]
@jovo 
The paper mentions additional data used to differentiate between "inhibitory" and "excitatory" neurons. Is there any additional data available? We may be able to create a more comprehensive model with this additional information.

**Comment by jovo** [comment]
Which paper?

**Comment by bvarjavand** [comment]
http://www.nature.com/nature/journal/v471/n7337/abs/nature09802.html
