### ISSUE TITLE
Regression and conditional dependence

### ISSUE THREAD

**Issue by jaylmiller** [Upward-Spiral-Science/team1#6]
If we assumed that unmasked is conditioned on x, y, z, and synapses, does the fact that one of our regressions had a very high r^2 value validate that assumption?

**Comment by jovo** [comment]
it is a complicated question :)
we can discuss in my office tues before class if you want...

On Sun, Mar 6, 2016 at 2:22 PM, Jay Miller notifications@github.com wrote:

> If we assumed that unmasked is conditioned on x, y, z, and synapses, does
> the fact that one of our regressions had a very high r^2 value validate
> that assumption?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/team1/issues/6.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by emarsh0000** [comment]
Hey guys! Not that I haven't loved the emails but I think there's been an error. I'm not actually in this group. ?

With Joy, Emily Marsh
805-458-3155

On Mar 6, 2016, at 8:12 PM, joshua vogelstein <notifications@github.com<mailto:notifications@github.com>> wrote:

it is a complicated question :)
we can discuss in my office tues before class if you want...

On Sun, Mar 6, 2016 at 2:22 PM, Jay Miller <notifications@github.com<mailto:notifications@github.com>> wrote:

> If we assumed that unmasked is conditioned on x, y, z, and synapses, does
> the fact that one of our regressions had a very high r^2 value validate
> that assumption?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/team1/issues/6.

## 

the glass is all full: half water, half air.
neurodata.iohttp://neurodata.io

##

**Comment by jaylmiller** [comment]
@jovo, i'd love to stop by and discuss before class.

thanks,
Jay

**Comment by jovo** [comment]
ok

On Mon, Mar 7, 2016 at 11:50 AM, Jay Miller notifications@github.com
wrote:

> @jovo https://github.com/jovo, i'd love to stop by and discuss before
> class.
> 
> thanks,
> Jay
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/team1/issues/6#issuecomment-193341258
> .

## 

the glass is all full:  half water, half air.
neurodata.io
