### ISSUE TITLE
A few questions about the data

### ISSUE THREAD

**Issue by jaylmiller** [Upward-Spiral-Science/team1#7]
1) I'm confused as to what exactly the source of the data is. In the data repo under syn-density, it is stated that the data comes from http://docs.neurodata.io/kasthuri2015/, meaning the corresponding paper would be this, http://www.cell.com/cell/fulltext/S0092-8674(15)00824-7, correct? But then it says the data can be visualized at http://viz.neurodata.io/bock11/, and from my understanding this data is from a different paper, specifically, http://www.nature.com/nature/journal/v471/n7337/full/nature09802.html. Sorry if I'm misunderstanding something, I am just confused as to what the source of the data is from?

2) Also I'm confused by the units in the data visualizer, specifically how they correspond with the units in the data we were given. Is there somewhere in the paper, or on the website (viz.neruodata.io) that you could point me to help understand this?

Thanks,
Jay

**Comment by jovo** [comment]
closed because you got satisfaction?

On Mon, Apr 18, 2016 at 8:19 PM, Jay Miller notifications@github.com
wrote:

> 1) I'm confused as to what exactly the source of the data is. In the data
> repo under syn-density, it is stated that the data comes from
> http://docs.neurodata.io/kasthuri2015/, meaning the corresponding paper
> would be this, http://www.cell.com/cell/fulltext/S0092-8674(15)00824-7,
> correct? But then it says the data can be visualized at
> http://viz.neurodata.io/bock11/, and from my understanding this data is
> from a different paper, specifically,
> http://www.nature.com/nature/journal/v471/n7337/full/nature09802.html.
> Sorry if I'm misunderstanding something, I am just confused as to what the
> source of the data is from?
> 
> 2) Also I'm confused by the units in the data visualizer, specifically how
> they correspond with the units in the data we were given. Is there
> somewhere in the paper, or on the website (viz.neruodata.io) that you
> could point me to help understand this?
> 
> Thanks,
> Jay
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/team1/issues/7

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jaylmiller** [comment]
yes i think i figured out the units and now the viz.neurodata.io makes much more sense... although since it seems that the data is from the Bock 2011 paper, i am still confused why the repo says our data comes from kasthuri 2015? unless theres some connection i'm missing (or i'm just incorrect)

edit: actually after rereading the kasthuri and looking at the data on the viz, i'm less sure... the relative dimensions (that is the ratio of height to width to depth etc..) seem to be more in line with the Bock 2011 paper but the units (i.e. range of possible x, y, and z) seem more inline with the kashthuri data.

**Comment by jovo** [comment]
word.  the data is totally from bock11, not sure why i wrote kasthuri.
maybe you can fix that? it is in github after all :)

On Tue, Apr 19, 2016 at 5:25 PM, Jay Miller notifications@github.com
wrote:

> yes i think i figured out the units and now the viz.neurodata.io makes
> much more sense... although since it seems that the data is from the Bock
> 2011 paper, i am still confused why the repo says our data comes from
> kasthuri 2015? unless theres some connection i'm missing (or i'm just
> incorrect)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/team1/issues/7#issuecomment-212136036

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jaylmiller** [comment]
thanks!

just submitted a pull request
